name: test

on:
    workflow_dispatch:
        inputs:
            test:
                description: 'stuffAndJunk'
                required: true

jobs:
    test:
      name: test job
      runs-on: ubuntu-latest
      steps:
        - name: step_one
          run: echo "test"
        - name: step_two
          run: echo "TWO"