name: repoBworkflow
on:
  repository_dispatch:
    types: [RepoAEvent]
jobs:
  repoBjobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: testBName
        run: |
          echo this event triggered.
