defaults:
  comment: "testing this probot thing"

matches:
  - description: "This is a comment description"
    regex: "getRawStuff"
  - regex: "fourth test"
    comment: "did this show up on the fourth test?"
  - regex: fourth test
    comment: "this one? "
  - regex: asdfTest
