name: commenter
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get file
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: "variables-to-check.yaml"
          from: "yaml"
          to: "json"

      - name: Get the file
        run: |
          echo ${{ steps.yaml2json.outputs.data }}
          echo "CONFIG=${{ steps.yaml2json.outputs.data }}" >> $GITHUB_ENV
      - name: print the file
        run: |
          echo "${{ env.CONFIG }}"
      - name: find matches
        uses: actions/github-script@v4
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const files = await github.request(diff_url)
            const file = files.data

      - name: make comment
        uses: actions/github-script@v4
        with:
          script: |
            const matchesPattern = (pattern, text) => {
              const regex = new RegExp(pattern);
              return !!text.match(regex)
            }

            const diff_url = context.payload.pull_request.diff_url
            const files = await github.request(diff_url)
            const file = files.data
            let position = 0

            file.split("\n").forEach((line) => {
              if (line.startsWith("+")){
                const addedLine = line.slice(1);
                const matches = ${{ steps.yaml2json.outputs.data }}
                console.log('MATCH', matches)

              }
              position += 1;
            })
