name: commenter
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get file
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: "variables-to-check.yaml"
          from: "yaml"
          to: "json"

      - name: Get the file
        run: |
          echo ${{ steps.yaml2json.outputs.data }}
          echo "CONFIG=${{ steps.yaml2json.outputs.data }}" >> $GITHUB_ENV

      - name: make comment
        uses: actions/github-script@v4
        with:
          script: |
            let BOT_NAME = 'github-actions[bot]'
            let review_id = ''
            const matchesPattern = (pattern, text) => {
              const regex = new RegExp(pattern);
              return !!text.match(regex)
            }
            // console.log("STUFF: ", context)

            let getReview = async () => {
              const allReviews =  await github.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              })
             // console.log("HEREEEE: ", allReviews)
              
              return allReviews.data.filter((comment) => {
                // console.log("IDName: ", comment)
                let review_id = comment.id
                console.log("reviewerree ", review_id)
                getTheCommentsGod(review_id)
                return comment.user.login === BOT_NAME })
            }

            getTheCommentsGod = async (reviewId) => {
              console.log("made it to getTheCommentsGod")
              const allComments =  await github.pulls.listCommentsForReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                review_id: reviewId
              })
              console.log("HEREEEE: ", allComments)
            }
            getReview()

            const commentAlreadyExists = (comments, position, potentialCommentText) => {
              return !!comments.find((comment) => {
                return comment.position === position && comment.body === potentialCommentText;
              })
            }
