name: commenter
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get file
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: "variables-to-check.yaml"
          from: "yaml"
          to: "json"

      - name: Get the file
        run: |
          echo ${{ steps.yaml2json.outputs.data }}
          echo "CONFIG=${{ steps.yaml2json.outputs.data }}" >> $GITHUB_ENV

      - name: make comment
        uses: actions/github-script@v4
        with:
          script: |
            let BOT_NAME = 'github-actions[bot]'

            const matchesPattern = (pattern, text) => {
              const regex = new RegExp(pattern);
              return !!text.match(regex)
            }

            let getBotComments = async (github, owner, repo, pullNumber, reviewId) => {
              const allComments =  await github.pulls.listReviews({
                owner,
                repo,
                pull_number: pullNumber,
                review_id: reviewId
              })
              return allComments.data.filter((comment) => {
                console.log("IDName: ", comment.user.login)
                return comment.user.login === BOT_NAME })
            }


            const commentAlreadyExists = (comments, position, potentialCommentText) => {
              return !!comments.find((comment) => {
                return comment.position === position && comment.body === potentialCommentText;
              })
            }

            const diff_url = context.payload.pull_request.diff_url
            const files = await github.request(diff_url)
            const file = files.data
            const botComments = await getBotComments(
              context.github,
              owner: context.repo.owner,
              repo: context.repo.repo,
              pullNumber: context.issue.number,
              reviewId: context.payload.pull_request.id
            )

            let position = 0
            let filePath = ''
            let arrayOfComments = []


            for(const line of file.split("\n")){
              if (line.startsWith("@@ ")){
                position = 0
              }
              else if (line.startsWith("+")){
                if(line.includes("+++")){
                  let parts = line.split("b/")
                  filePath  = parts.pop();
                  console.log("FILEPATH", filePath)
                }
                const addedLine = line.slice(1);
                const matches = ${{ steps.yaml2json.outputs.data }}

                for(const match of matches.matches){
                  const commentText = match.comment ? match.comment : matches.defaults.comment;
                  if (matchesPattern(match.regex, addedLine)) {
                    singleComment = {
                      path: filePath,
                      position: position,
                      body: (commentText + addedLine)
                    }
                    arrayOfComments.push(singleComment)
                  }
                }

              }
              position += 1;
            }
            github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                commit_id: '${{ github.event.pull_request.head.sha }}',
                event: "COMMENT",
                comments: arrayOfComments,
            })
