name: commenter
on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          script: |
            npm install js-yaml
            const script = require('./script.js')
            console.log(script({github, context}))
            await script
