name: commenter
on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get file
        run: |
          test=`cat variables-to-check.yaml`
          echo "TERST " test
      - name: find matches
        uses: actions/github-script@v4
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const files = await github.request(diff_url)
            const file = files.data

      - name: make comment
        uses: actions/github-script@v4
        with:
          script: |
            const ownerRef = context.repo.owner;
            const repoRef = context.repo.repo;
            const commitIdRef = context.sha
            const pullNumberRef = context.payload.number


            github.pulls.createReviewComment({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'A MATCH MIGHT BE HERE',
              commit_id: '${{ github.event.pull_request.head.sha }}',
              position: 1,
              path: "README.md"
            })
