name: commenter
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get file
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: "variables-to-check.yaml"
          from: "yaml"
          to: "json"

      - name: Get the file
        run: |
          echo ${{ steps.yaml2json.outputs.data }}
          echo "CONFIG=${{ steps.yaml2json.outputs.data }}" >> $GITHUB_ENV

      - name: make comment
        uses: actions/github-script@v4
        with:
          script: |
            const matchesPattern = (pattern, text) => {
              const regex = new RegExp(pattern);
              return !!text.match(regex)
            }
            // console.log("LOGGGG ", context)
            console.log("IDIDID ", context.payload.pull_request.id)

            let allCommentsPrint = async () => {
              const allComments =  await github.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                review_id: context.payload.pull_request.id
              })
              console.log('COMMENTS', allComments.data)
            }
            allCommentsPrint()

            // const commentAlreadyExists = (comments, position, potentialCommentText) => {
            //   return !!comments.find((comment) => {
            //     return comment.position === position && comment.body === potentialCommentText;
            //   })
            // }
