name: commenter
on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get file
        run: |
          cat variables-to-check.yaml
      - name: find matches
        id: test
        run: |
          echo "You CAN deploy main to internal dev or mm100-dev to dev or test"

      - name: make comment
        uses: actions/github-script@v4
        with:
          script: |
            github.pulls.createReviewComment({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'A MATCH MIGHT BE HERE',
              commit_id: '${{ github.event.pull_request.head.sha }}',
              position: 1,
              path: "README.md"
            })
