name: commenter
on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install js-yaml
      - uses: actions/github-script@v4
        with:
          script: |
            github.pulls.createReviewComment({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a fake comment',
              commit_id: '${{ github.event.pull_request.head.sha }}',
              position: 1,
              path: "README.md"
            })
