name: commenter
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get file
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: "variables-to-check.yaml"
          from: "yaml"
          to: "json"

      - name: Print the file
        run: |
          export CONFIG=${{ steps.yaml2json.outputs.data }}
          echo $CONFIG
      - name: find matches
        uses: actions/github-script@v4
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const files = await github.request(diff_url)
            const file = files.data

      - name: make comment
        uses: actions/github-script@v4
        with:
          script: |
            const matchesPattern = (pattern, text) => {
              const regex = new RegExp(pattern);
              return !!text.match(regex)
            }

            const diff_url = context.payload.pull_request.diff_url
            const files = await github.request(diff_url)
            const file = files.data
            let position = 0

            github.pulls.createReviewComment({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a fake comment',
              commit_id: '${{ github.event.pull_request.head.sha }}',
              position: 1,
              path: "script.js"
            })
