name: Convert

on: push

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: "0"
      - name: test
        uses: fabasoad/data-format-converter-action@main
        id: yaml2json
        with:
          input: "variables-to-check.yaml"
          from: "yaml"
          to: "json"

      - name: Print result
        run: echo "${{ steps.yaml2json.outputs.output }}"
